TARGET =circle celsius2Fahr fahr2Celsius fahr2Celsius2 Fahr2Celsius3 limits literal score triangle

all: ${TARGET}

circle: $@

celsius2Fahr: $@

Fahr2Celsius: $@

Fahr2Celsius2: $@

Fahr2Celsius3: $@

limits: $@

ilteral: $@

score: $@

triangle: $@

clean:
	rm -f ${TARGET}